### ISSUE TITLE
Ch 9 spec fails

### ISSUE THREAD

**Issue by arturtr** [everydayrails/rails-4-1-rspec-3-0#48]
`spec/controllers/contacts_controller_spec.rb:199` fails with

```
Failures:

  1) ContactsController administrator access behaves like full access to contacts PATCH #update invalid attributes does not change the contact's attributes
     Failure/Error: expect(assigns(:contact).reload.attributes).to eq contact.attributes

       expected: {"id"=>2, "firstname"=>"Lawrence", "lastname"=>"Smith", "email"=>"evert.gottlieb@carter.com", "created_at"=>Thu, 08 Jan 2015 06:18:40 UTC +00:00, "updated_at"=>Thu, 08 Jan 2015 06:18:40 UTC +00:00, "hidden"=>false}
            got: {"id"=>2, "firstname"=>"Lawrence", "lastname"=>"Smith", "email"=>"evert.gottlieb@carter.com", "created_at"=>Thu, 08 Jan 2015 06:18:40 UTC +00:00, "updated_at"=>Thu, 08 Jan 2015 06:18:40 UTC +00:00, "hidden"=>false}

       (compared using ==)

       Diff:

     Shared Example Group: "full access to contacts" called from ./spec/controllers/contacts_controller_spec.rb:233
     # ./spec/controllers/contacts_controller_spec.rb:199:in `block (5 levels) in <top (required)>'
     # ./spec/rails_helper.rb:38:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:37:in `block (2 levels) in <top (required)>'

  2) ContactsController user access behaves like full access to contacts PATCH #update invalid attributes does not change the contact's attributes
     Failure/Error: expect(assigns(:contact).reload.attributes).to eq contact.attributes

       expected: {"id"=>2, "firstname"=>"Lawrence", "lastname"=>"Smith", "email"=>"danika@wilderman.com", "created_at"=>Thu, 08 Jan 2015 06:18:41 UTC +00:00, "updated_at"=>Thu, 08 Jan 2015 06:18:41 UTC +00:00, "hidden"=>false}
            got: {"id"=>2, "firstname"=>"Lawrence", "lastname"=>"Smith", "email"=>"danika@wilderman.com", "created_at"=>Thu, 08 Jan 2015 06:18:41 UTC +00:00, "updated_at"=>Thu, 08 Jan 2015 06:18:41 UTC +00:00, "hidden"=>false}

       (compared using ==)

       Diff:

     Shared Example Group: "full access to contacts" called from ./spec/controllers/contacts_controller_spec.rb:242
     # ./spec/controllers/contacts_controller_spec.rb:199:in `block (5 levels) in <top (required)>'
     # ./spec/rails_helper.rb:38:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:37:in `block (2 levels) in <top (required)>'
```

in branch  https://github.com/everydayrails/rails-4-1-rspec-3-0/tree/09_speedup
